### ISSUE TITLE
[FRONT-END] {TODAY} - page when deliveries are all done

### ISSUE THREAD

**Issue by cdjamalov** [hack4impact-mcgill/MADA-v2#70]
<img width="199" alt="Screenshot 2023-02-07 at 7 11 42 PM" src="https://user-images.githubusercontent.com/52832108/217395849-0435fed4-8fbd-42d9-84c6-87e6383ed5c3.png">

**Comment by steph-fontaine** [comment]
For this issue, no need to create a new page. Simply if delivery list is empty => show "Congratulations!" else => list of current directories
