### ISSUE TITLE
[FRONT-END] {USER PROFILE} personal information

### ISSUE THREAD

**Issue by cdjamalov** [hack4impact-mcgill/MADA-v2#72]
- photo for user to input, along with their name and title
- Account information: username, email, contact phone number
- Save changes or cancel
<img width="262" alt="Screenshot 2023-02-08 at 2 33 24 PM" src="https://user-images.githubusercontent.com/52832108/217632904-ed81e91a-3065-4d7b-b0cd-ddfdfbf71127.png">

**Comment by selenajin99** [comment]
closed by PR#84
