### ISSUE TITLE
[FRONT-END] {MARK AVAILABILITY} - calendar

### ISSUE THREAD

**Issue by cdjamalov** [hack4impact-mcgill/MADA-v2#74]
<img width="612" alt="Screenshot 2023-02-08 at 2 47 53 PM" src="https://user-images.githubusercontent.com/52832108/217635810-22055082-3a56-4878-a525-9b373a086b2e.png">
<img width="217" alt="Screenshot 2023-02-08 at 2 49 39 PM" src="https://user-images.githubusercontent.com/52832108/217636220-d8d69bb4-d7ac-4fcd-bfe6-747691ae2b9a.png">

However, thinking of potentially a when2meet style so we can allow for more flexibility for users such as 9-10:30am availability.

- save and cancel button

**Comment by selenajin99** [comment]
Use this design instead: https://dribbble.com/shots/19917842-Schedule-creation

<img width="557" alt="image" src="https://user-images.githubusercontent.com/68762346/217645938-fd88ba58-e18a-4175-9edd-c74b9ef40c83.png">
